<!--Desenvolvido por Rafael F. Santos - mfa.rafael@gmail.com-->
# <font color='blue'>Estatística Básica 10ª Edição</font>
### <font color='blue'>Wilton de O. Bussad</font>
### <font color='blue'>Pedro A. Morettin</font>

# Capítulo 02 - Resumo dos Dados

In [1]:
# Instalar/atualizar o pacote/biblioteca watermark para documentação
!pip install -q -U watermark

In [2]:
# Inicializar o pacote/biblioteca watermark
%reload_ext watermark
%watermark -a 'Rafael F. Santos'

Author: Rafael F. Santos

In [3]:
# Instalar/atualizar os pacotes/bibliotecas utilizados no Jupyter Notebook

In [4]:
# Importar pacotes/bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Importar dados
tab21 = pd.read_csv('raw/tabela2_1.csv', sep=';')

# Equivalente em R
# tab21 <- read.table('tabela2_1.csv', dec=',', sep=';', h=T)

In [6]:
# Verificar quais são as variáveis (nomes das colunas).
tab21.columns

# Equivalente em R
#names(tab21)

Index(['N', 'estado_civil', 'grau_instrucao', 'n_filhos', 'salario',
       'idade_anos', 'idade_meses', 'reg_procedencia'],
      dtype='str')

In [7]:
# Visualizar uma amotra do dataset (topo)
tab21.head(10)

,N,estado_civil,grau_instrucao,n_filhos,salario,idade_anos,idade_meses,reg_procedencia
0,1,solteiro,ensino fundamental,NaN,"4,00",26,3,interior
1,2,casado,ensino fundamental,1.0,"4,56",32,10,capital
2,3,casado,ensino fundamental,2.0,"5,25",36,5,capital
3,4,solteiro,ensino médio,NaN,"5,73",20,10,outra
4,5,solteiro,ensino fundamental,NaN,"6,26",40,7,outra
5,6,casado,ensino fundamental,0.0,"6,66",28,0,interior
6,7,solteiro,ensino fundamental,NaN,"6,86",41,0,interior
7,8,solteiro,ensino fundamental,NaN,"7,39",43,4,capital
8,9,casado,ensino médio,1.0,"7,59",34,10,capital
9,10,solteiro,ensino médio,NaN,"7,44",23,6,outra

In [8]:
# Criar a tabela de frequências
# Define a ordem desejada para a variável qualitativa ordinal
ordem = ['ensino fundamental',
         'ensino médio',
         'superior']

# Calcula a frequência absoluta (ni) de cada categoria
# e reorganiza o resultado conforme a ordem definida
frequencia = tab21['grau_instrucao'].value_counts().reindex(ordem)

# Calcula a frequência relativa (fi), em proporção,
# e reorganiza conforme a ordem definida
proporcao = tab21['grau_instrucao'].value_counts(normalize=True).reindex(ordem)

# Converte a proporção para porcentagem
porcentagem = proporcao * 100

# Cria a tabela de distribuição de frequências
dist_frequencias = pd.DataFrame({'Frequência (ni)': frequencia,
                                 'Proporção (fi)': round(proporcao, 2),
                                 'Porcentagem (100 fi)': round(porcentagem, 2)})

# Adiciona uma linha com os totais das colunas
dist_frequencias.loc['Total'] = [dist_frequencias['Frequência (ni)'].sum(),
                                 dist_frequencias['Proporção (fi)'].sum(),
                                 dist_frequencias['Porcentagem (100 fi)'].sum()]

# Exibe a tabela final
dist_frequencias

                    Frequência (ni)  Proporção (fi)  Porcentagem (100 fi)
grau_instrucao
ensino fundamental             12.0            0.33                 33.33
ensino médio                   18.0            0.50                 50.00
superior                        6.0            0.17                 16.67
Total                          36.0            1.00                100.00

### Desafio - Construir a tabela de distribuição de frequências intervalar para salários

In [ ]:
# Criar a tabela de distribuição de frequências intervalar para salários
tab21['salario'] = list(map(lambda x: float(x.replace(',', '.')), tab21['salario']))

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   N                36 non-null     int64
 1   estado_civil     36 non-null     str
 2   grau_instrucao   36 non-null     str
 3   n_filhos         20 non-null     float64
 4   salario          36 non-null     float64
 5   idade_anos       36 non-null     int64
 6   idade_meses      36 non-null     int64
 7   reg_procedencia  36 non-null     str
dtypes: float64(2), int64(3), str(3)
memory usage: 3.3 KB

In [22]:
frequencia_sal = tab21[tab21['salario'] < 8.0].value_counts()
frequencia_sal

N  estado_civil  grau_instrucao      n_filhos  salario  idade_anos  idade_meses  reg_procedencia
2  casado        ensino fundamental  1.0       4.56     32          10           capital            1
3  casado        ensino fundamental  2.0       5.25     36          5            capital            1
6  casado        ensino fundamental  0.0       6.66     28          0            interior           1
9  casado        ensino médio        1.0       7.59     34          10           capital            1
Name: count, dtype: int64

In [10]:
# Autor do Projeto
%reload_ext watermark
%watermark -a 'Rafael F. Santos'

Author: Rafael F. Santos

In [11]:
# Exibir informações dos pacotes/bibliotecas
%watermark --iversions

matplotlib: 3.11.2
numpy     : 2.4.6
pandas    : 3.0.6

In [12]:
# Exibir informações da Linguagem Python e do Sistema Operacional
%watermark -v -m

Python implementation: CPython
Python version       : 3.14.8
IPython version      : 9.17.1

Compiler    : GCC 14.3.0
OS          : Linux
Release     : 7.1.5-76070105-generic
Machine     : x86_64
Processor   :
CPU cores   : 20
Architecture: 64bit

### FIM.